# Generated by Django 3.1 on 2020-08-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthtoken',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
