# Generated by Django 3.1 on 2020-08-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200818_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthtoken',
            name='token',
            field=models.CharField(max_length=300),
        ),
    ]
